# Generated by Django 5.2.1 on 2025-05-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_problem_options_problem_input_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={},
        ),
        migrations.AddField(
            model_name='problem',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input_description',
            field=models.TextField(help_text='Description of input format'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=256),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_description',
            field=models.TextField(help_text='Description of output format'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=1),
        ),
    ]
