# Generated by Django 5.2.1 on 2025-06-11 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_problemtestcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='Enter the input for the test case')),
                ('expected_output', models.TextField(help_text='Enter the expected output')),
                ('is_sample', models.BooleanField(default=False, help_text='Is this a sample test case?')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='problems.problem')),
            ],
        ),
        migrations.DeleteModel(
            name='ProblemTestCase',
        ),
    ]
